config/routes.rb
WiCity::Application.routes.draw do

  resources :links

  resources :nodos

  devise_for :users

  get '/users/sign_in', to: 'home#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :pharms
  resources :parks
  resources :taxistations
  resources :radiotaxis
  resources :fuels
  resources :restaurants
  resources :first_aids
  resources :hospitals
  resources :schools
  resources :caves

  root 'home#index'

  get '/intloc', to: 'home#intloc'
  get '/nearserv', to: 'home#nearserv'
  get '/recnearserv', to: 'home#recnearserv'

  get '/alllinks', to: 'links#showall'
  get '/allnodos', to: 'nodos#showall'

end

app/models/cafe.rb
class Cafe < ActiveRecord::Base
end

app/models/first_aid.rb
class FirstAid < ActiveRecord::Base
end

app/models/fuel.rb
class Fuel < ActiveRecord::Base

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/nodo.rb
class Nodo < ActiveRecord::Base
end

app/models/park.rb
class Park < ActiveRecord::Base

  validate :occupati_cannot_be_greater_than_capacity, :occupati_cannot_be_min_zero

  #validates :occupati, numericality: true
  validates :capacity, numericality: true

  def occupati_cannot_be_greater_than_capacity
    if !occupati.nil? && !capacity.nil?
      if occupati > capacity
        errors.add(:occupati, "can't be greater than capacity")
      end
    end
  end

  def occupati_cannot_be_min_zero
    if !occupati.nil?
      if occupati < 0
        errors.add(:occupati, "can't be less than zero")
      end
    end
  end

end

app/models/pharm.rb
class Pharm < ActiveRecord::Base
end

app/models/radiotaxi.rb
class Radiotaxi < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/taxistation.rb
class Taxistation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/first_aids_controller.rb
class FirstAidsController < ApplicationController
  before_action :set_first_aid, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /first_aids
  # GET /first_aids.json
  def index
    @today = Time.now.strftime("%u")  # => lun = 1, mar = 2, mer = 3
    @t = Time.now

    @first_aids = FirstAid.all
  end

  # GET /first_aids/1
  # GET /first_aids/1.json
  def show
  end

  # GET /first_aids/new
  def new
    @first_aid = FirstAid.new
  end

  # GET /first_aids/1/edit
  def edit
  end

  # POST /first_aids
  # POST /first_aids.json
  def create
    @first_aid = FirstAid.new(first_aid_params)

    respond_to do |format|
      if @first_aid.save
        format.html { redirect_to @first_aid, notice: 'first aid was successfully created.' }
        format.json { render action: 'show', status: :created, location: @first_aid }
      else
        format.html { render action: 'new' }
        format.json { render json: @first_aid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /first_aids/1
  # PATCH/PUT /first_aids/1.json
  def update
    respond_to do |format|
      if @first_aid.update(first_aid_params)
        format.html { redirect_to @first_aid, notice: 'first aid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @first_aid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /first_aids/1
  # DELETE /first_aids/1.json
  def destroy
    @first_aid.destroy
    respond_to do |format|
      format.html { redirect_to first_aids_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_first_aid
      @first_aid = FirstAid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def first_aid_params
      params.require(:first_aid).permit(:name, :address, :lat, :lng, :LM, :LP, :MM, :MP, :MEM, :MEP, :GM, :GP, :VM, :VP, :SM, :SP, :DM, :DP)
    end
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/helpers/first_aids_helper.rb
module FirstAidsHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/nodos_helper.rb
module NodosHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/pharms_helper.rb
module PharmsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/first_aids/edit.html.erb
<div data-role="header" data-theme="b">
  <h1>Edit First Aid</h1>
  <%= link_to 'Back', hospitals_path+'?filter1=now', 'data-icon' => 'back', 'class' => 'ui-btn-left', :target => '_parent' %>
  <%= link_to 'Show', @first_aid, :target => '_parent', 'data-icon' => 'search', 'class' => 'ui-btn-right'  %>
</div>

<%= render 'form_edit' %>

app/views/first_aids/new.html.erb
<div data-role="header" data-theme="b">
  <h1>New First Aid</h1>
  <%= link_to 'Back', hospitals_path+'?filter1=now', 'data-icon' => 'back', 'class' => 'ui-btn-left', :target => '_parent' %>
</div>

<%= render 'form_new' %>

app/views/first_aids/show.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true"></script>

<script type="text/javascript">

    var map;
    var geocoder;
    var mypos = 0;

    var check = 0;

    var directionsDisplay;
    var directionsService = new google.maps.DirectionsService();

    var stepDisplay;
    var markerArray = [];

    var intervall = window.setInterval(checkpos, 2000);

    function checkpos() {
        if(mypos == 0) {
            check++;
            preinit();
        }
    }

    function preinit() {
        geocoder = new google.maps.Geocoder();

        var lat = "<%= params[:lat] %>";
        var lng = "<%= params[:lng] %>";
        if(lat) {
            mypos = new google.maps.LatLng(lat, lng);
            window.clearInterval(intervall);
            initialize();
        }
        else {
            if(check > 1) {
                window.clearInterval(intervall);
                initialize();
            }
            else {
                if(navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(function(position) {
                        if(position.coords.latitude) {
                            mypos = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                            window.clearInterval(intervall);
                            initialize();
                        }
                    }, function() {
                        handleNoGeolocation(true);
                    });
                } else {
                    handleNoGeolocation(false);
                }
            }
        }
    }

    function codeAdd(add) {
        geocoder.geocode( { 'address': add}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                mypos = results[0].geometry.location;
            } else {
                mypos = 0;
            }
            window.clearInterval(intervall);
            initialize();
        });
    }

    function handleNoGeolocation(errorFlag) {
        if (errorFlag) {
            alert("Error: The Geolocation service failed.");
        } else {
            alert("Error: Your browser doesn\'t support geolocation.");
        }
    }

    function initialize() {
        if(mypos == 0) {
            <% if user_signed_in? %>
            if("<%= current_user.prefadd %>" == "away") {
                codeAdd("<%= current_user.away %>");
            }
            else if("<%= current_user.prefadd %>" == "home") {
                codeAdd("<%= current_user.home %>");
            }
            else if("<%= current_user.prefadd %>" == "office") {
                codeAdd("<%= current_user.office %>");
            }
            else if("<%= current_user.prefadd %>" == "other") {
                codeAdd("<%= current_user.other %>");
            }
            else {
                mypos = new google.maps.LatLng(37.508059, 375.082752);
            }
            <% else %>
            mypos = new google.maps.LatLng(37.508059, 375.082752);
            <% end %>
        }

        directionsDisplay = new google.maps.DirectionsRenderer({suppressMarkers: true});

        var mapOptions = {
            center: new google.maps.LatLng(-34.397, 150.644),
            zoom: 17,
            minZoom: 12,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
        directionsDisplay.setMap(map);

        directionsDisplay.setPanel(document.getElementById('directions-panel'));
        $( "#directions-panel" ).trigger( "updatelayout" );

        stepDisplay = new google.maps.InfoWindow();

        codeAddress("<%= @first_aid.address %>");
    }

    function codeAddress(add) {
        var address = add;
        var s = "<%= params[:s] %>";
        geocoder.geocode( { 'address': address}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                map.setCenter(results[0].geometry.location);
                if(s=="close") {
                    var icon = '/assets/marker/cfirst_aid.png';
                }
                else {
                    var icon = '/assets/marker/first_aid.png';
                }
                var marker = new google.maps.Marker({
                    map: map,
                    position: results[0].geometry.location,
                    icon: icon
                });
                google.maps.event.addListener(marker, "dblclick", function (e) {
                    <%    if params[:time]   %>
                    location.href='../nearserv?lat='+e.latLng.lat()+'&lng='+e.latLng.lng()+'&time=<%= params[:time] %>';
                    <%    else   %>
                    location.href='../nearserv?lat='+e.latLng.lat()+'&lng='+e.latLng.lng();
                    <%    end   %>
                });
            } else {
                alert("Geocode was not successful for the following reason: " + status);
            }
        });
    }

    function calcRoute(mode) {

        for (var i = 0; i < markerArray.length; i++) {
            markerArray[i].setMap(null);
        }

        var selectedMode = mode;
        var request = {
            origin: mypos,
            destination: "<%= @first_aid.address %>",
            travelMode: google.maps.TravelMode[selectedMode]
        };
        directionsService.route(request, function(response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
                showSteps(response);
            }
        });
    }

    function showSteps(directionResult) {
        var myRoute = directionResult.routes[0].legs[0];

        for (var i = 0; i < myRoute.steps.length; i++) {
            var marker = new google.maps.Marker({
                position: myRoute.steps[i].start_point,
                map: map
            });
            attachInstructionText(marker, myRoute.steps[i].instructions);
            markerArray[i] = marker;

            google.maps.event.addListener(marker, "dblclick", function (e) {
                <%    if params[:time]   %>
                location.href='../nearserv?lat='+e.latLng.lat()+'&lng='+e.latLng.lng()+'&time=<%= params[:time] %>';
                <%    else   %>
                location.href='../nearserv?lat='+e.latLng.lat()+'&lng='+e.latLng.lng();
                <%    end   %>
            });
        }
    }

    function attachInstructionText(marker, text) {
        google.maps.event.addListener(marker, 'click', function() {
            stepDisplay.setContent(text);
            stepDisplay.open(map, marker);
        });
    }

    //google.maps.event.addDomListener(window, 'load', preinit);
    //google.maps.event.addDomListener(window, 'load', initialize);

</script>

<style>
    .ui-panel-inner {
        overflow: scroll;
        -webkit-overflow-scrolling: touch;
    }

    .ui-panel.ui-panel-open {
        position:fixed;
    }

    #directions-panel {
        height: 100%;
        overflow: auto;
        -webkit-overflow-scrolling: touch;
    }

</style>

<div data-role="header" data-theme="b">
  <h1><%= @first_aid.name %></h1>
  <div class="ui-btn-left" data-role="controlgroup" data-type="horizontal" data-mini="true">
    <%= link_to 'Back', hospitals_path+'?filter1=now', 'data-icon' => 'back', 'data-role' => 'button', 'data-iconpos' => 'notext', :target => '_parent' %>
    <%= link_to 'Home', root_url, 'data-icon' => 'home', 'data-role' => 'button', 'data-iconpos' => 'notext', :target => '_parent' %>
  </div>
  <%= link_to 'Edit', edit_first_aid_path(@first_aid), 'data-icon' => 'edit', 'class' => 'ui-btn-right', 'data-iconpos' => 'notext', :target => '_parent' %>
</div>


<div data-role="content">

  <%    if params[:time]
          datatempo = params[:time]
          year = datatempo.split("-")[0].to_s
          day = datatempo.split("-")[2].to_s.split(" ")[0].to_s
          mese = datatempo.split("-")[1].to_s
          ora = datatempo.split(" ")[1].split(":")[0].to_s
          min = datatempo.split(" ")[1].split(":")[1].to_s

          data = day+'/'+mese+'/'+year+'  -  '+ora+':'+min
        else
          t = Time.now
          data = t.strftime("%d/%m/%Y  -  %H:%M")
        end
  %>
  <input disabled="" value="<%= data %>" type="button" data-icon="clock">

  <div class="ui-bar ui-bar-c ui-corner-all ui-shadow">
    <div id="map-canvas" style="width: 100%; height: 400px" class="ui-corner-all ui-shadow"></div>
  </div>

  <div class="ui-grid-a ui-responsive">
    <div class="ui-block-a">
      <a href="#popupMenu" data-rel="popup" data-role="button" data-position-to='window' data-transition="slideup" data-icon="gear" data-theme="b">Get Direction</a>
    </div>
    <div class="ui-block-b">
      <a href="#directions-panel" data-role="button" data-transition="slideup" data-icon="gear" data-theme="b">Panel</a>
    </div>
  </div>

  <div>
    <div data-role="popup" id="popupMenu">
      <a href="#" data-rel="back" data-role="button" data-theme="a" data-icon="delete" data-iconpos="notext" class="ui-btn-right">Close</a>
      <ul data-role="listview" data-inset="true" style="min-width:210px;">
        <li><a href="" onclick="calcRoute('DRIVING');" data-rel="back">Driving</a></li>
        <li><a href="" onclick="calcRoute('WALKING');" data-rel="back">Walking</a></li>
        <li><a href="" onclick="calcRoute('BICYCLING');" data-rel="back">Bicycling</a></li>
      </ul>
    </div>
  </div>

  <!-- <div id="directions-panel"></div> -->

  <div data-role="panel" id="directions-panel" data-display="overlay" class="ui-responsive-panel"></div>

  <p>
    <strong>Address:</strong>
    <%= @first_aid.address %>
  </p>

  <div class="ui-grid-b ui-corner-all ui-shadow">

    <div class="ui-block-a">
      <div class="ui-bar ui-bar-a ui-corner-top" style="height:25px" id="text-lun">Lunedì</div>
    </div>
    <div class="ui-block-b">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.LM %></div>
    </div>
    <div class="ui-block-c">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.LP %></div>
    </div>


    <div class="ui-block-a">
      <div class="ui-bar ui-bar-a" style="height:25px">Martedì</div>
    </div>
    <div class="ui-block-b">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.MM %></div>
    </div>
    <div class="ui-block-c">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.MP %></div>
    </div>


    <div class="ui-block-a">
      <div class="ui-bar ui-bar-a" style="height:25px">Mercoledì</div>
    </div>
    <div class="ui-block-b">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.MEM %></div>
    </div>
    <div class="ui-block-c">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.MEP %></div>
    </div>


    <div class="ui-block-a">
      <div class="ui-bar ui-bar-a" style="height:25px">Giovedì</div>
    </div>
    <div class="ui-block-b">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.GM %></div>
    </div>
    <div class="ui-block-c">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.GP %></div>
    </div>


    <div class="ui-block-a">
      <div class="ui-bar ui-bar-a" style="height:25px">Venerdì</div>
    </div>
    <div class="ui-block-b">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.VM %></div>
    </div>
    <div class="ui-block-c">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.VP %></div>
    </div>


    <div class="ui-block-a">
      <div class="ui-bar ui-bar-a" style="height:25px">Sabato</div>
    </div>
    <div class="ui-block-b">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.SM %></div>
    </div>
    <div class="ui-block-c">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.SP %></div>
    </div>


    <div class="ui-block-a">
      <div class="ui-bar ui-bar-a" style="height:25px">Domenica</div>
    </div>
    <div class="ui-block-b">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.DM %></div>
    </div>
    <div class="ui-block-c">
      <div class="ui-bar ui-bar-a" style="height:25px"><%= @first_aid.DP %></div>
    </div>

  </div>

</div>