config/routes.rb
WiCity::Application.routes.draw do

  resources :links

  resources :nodos

  devise_for :users

  get '/users/sign_in', to: 'home#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :pharms
  resources :parks
  resources :taxistations
  resources :radiotaxis
  resources :fuels
  resources :restaurants
  resources :first_aids
  resources :hospitals
  resources :schools
  resources :caves

  root 'home#index'

  get '/intloc', to: 'home#intloc'
  get '/nearserv', to: 'home#nearserv'
  get '/recnearserv', to: 'home#recnearserv'

  get '/alllinks', to: 'links#showall'
  get '/allnodos', to: 'nodos#showall'

end

app/models/cafe.rb
class Cafe < ActiveRecord::Base
end

app/models/first_aid.rb
class FirstAid < ActiveRecord::Base
end

app/models/fuel.rb
class Fuel < ActiveRecord::Base

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/nodo.rb
class Nodo < ActiveRecord::Base
end

app/models/park.rb
class Park < ActiveRecord::Base

  validate :occupati_cannot_be_greater_than_capacity, :occupati_cannot_be_min_zero

  #validates :occupati, numericality: true
  validates :capacity, numericality: true

  def occupati_cannot_be_greater_than_capacity
    if !occupati.nil? && !capacity.nil?
      if occupati > capacity
        errors.add(:occupati, "can't be greater than capacity")
      end
    end
  end

  def occupati_cannot_be_min_zero
    if !occupati.nil?
      if occupati < 0
        errors.add(:occupati, "can't be less than zero")
      end
    end
  end

end

app/models/pharm.rb
class Pharm < ActiveRecord::Base
end

app/models/radiotaxi.rb
class Radiotaxi < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/taxistation.rb
class Taxistation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/caves_controller.rb
class CavesController < ApplicationController
  before_action :set_cafe, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /caves
  # GET /caves.json
  def index
    @today = Time.now.strftime("%u")  # => lun = 1, mar = 2, mer = 3
    @t = Time.now

    @caves = Cafe.all
  end

  # GET /caves/1
  # GET /caves/1.json
  def show
  end

  # GET /caves/new
  def new
    @cafe = Cafe.new
  end

  # GET /caves/1/edit
  def edit
  end

  # POST /caves
  # POST /caves.json
  def create
    @cafe = Cafe.new(cafe_params)

    respond_to do |format|
      if @cafe.save
        format.html { redirect_to @cafe, notice: 'Cafe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cafe }
      else
        format.html { render action: 'new' }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caves/1
  # PATCH/PUT /caves/1.json
  def update
    respond_to do |format|
      if @cafe.update(cafe_params)
        format.html { redirect_to @cafe, notice: 'Cafe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caves/1
  # DELETE /caves/1.json
  def destroy
    @cafe.destroy
    respond_to do |format|
      format.html { redirect_to caves_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cafe
      @cafe = Cafe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cafe_params
      params.require(:cafe).permit(:name, :address, :lat, :lng, :LM, :LP, :MM, :MP, :MEM, :MEP, :GM, :GP, :VM, :VP, :SM, :SP, :DM, :DP)
    end
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/nodos_helper.rb
module NodosHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/pharms_helper.rb
module PharmsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/caves/_form.html.erb
<%= form_for(@cafe) do |f| %>
  <% if @cafe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cafe.errors.count, "error") %> prohibited this cafe from being saved:</h2>

      <ul>
      <% @cafe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :LM %><br>
    <%= f.text_field :LM %>
  </div>
  <div class="field">
    <%= f.label :LP %><br>
    <%= f.text_field :LP %>
  </div>
  <div class="field">
    <%= f.label :MM %><br>
    <%= f.text_field :MM %>
  </div>
  <div class="field">
    <%= f.label :MP %><br>
    <%= f.text_field :MP %>
  </div>
  <div class="field">
    <%= f.label :MEM %><br>
    <%= f.text_field :MEM %>
  </div>
  <div class="field">
    <%= f.label :MEP %><br>
    <%= f.text_field :MEP %>
  </div>
  <div class="field">
    <%= f.label :GM %><br>
    <%= f.text_field :GM %>
  </div>
  <div class="field">
    <%= f.label :GP %><br>
    <%= f.text_field :GP %>
  </div>
  <div class="field">
    <%= f.label :VM %><br>
    <%= f.text_field :VM %>
  </div>
  <div class="field">
    <%= f.label :VP %><br>
    <%= f.text_field :VP %>
  </div>
  <div class="field">
    <%= f.label :SM %><br>
    <%= f.text_field :SM %>
  </div>
  <div class="field">
    <%= f.label :SP %><br>
    <%= f.text_field :SP %>
  </div>
  <div class="field">
    <%= f.label :DM %><br>
    <%= f.text_field :DM %>
  </div>
  <div class="field">
    <%= f.label :DP %><br>
    <%= f.text_field :DP %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caves/edit.html.erb
<div data-role="header" data-theme="b">
  <h1>Edit café</h1>
  <%= link_to 'Back', restaurants_path+'?filter1=now', 'data-icon' => 'back', 'class' => 'ui-btn-left', :target => '_parent' %>
  <%= link_to 'Show', @restaurant, :target => '_parent', 'data-icon' => 'search', 'class' => 'ui-btn-right'  %>
</div>

<%= render 'form_edit' %>

app/views/caves/index.html.erb
<h1>Listing caves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Lm</th>
      <th>Lp</th>
      <th>Mm</th>
      <th>Mp</th>
      <th>Mem</th>
      <th>Mep</th>
      <th>Gm</th>
      <th>Gp</th>
      <th>Vm</th>
      <th>Vp</th>
      <th>Sm</th>
      <th>Sp</th>
      <th>Dm</th>
      <th>Dp</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @caves.each do |cafe| %>
      <tr>
        <td><%= cafe.name %></td>
        <td><%= cafe.address %></td>
        <td><%= cafe.lat %></td>
        <td><%= cafe.lng %></td>
        <td><%= cafe.LM %></td>
        <td><%= cafe.LP %></td>
        <td><%= cafe.MM %></td>
        <td><%= cafe.MP %></td>
        <td><%= cafe.MEM %></td>
        <td><%= cafe.MEP %></td>
        <td><%= cafe.GM %></td>
        <td><%= cafe.GP %></td>
        <td><%= cafe.VM %></td>
        <td><%= cafe.VP %></td>
        <td><%= cafe.SM %></td>
        <td><%= cafe.SP %></td>
        <td><%= cafe.DM %></td>
        <td><%= cafe.DP %></td>
        <td><%= link_to 'Show', cafe %></td>
        <td><%= link_to 'Edit', edit_cafe_path(cafe) %></td>
        <td><%= link_to 'Destroy', cafe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cafe', new_cafe_path %>

app/views/caves/new.html.erb
<div data-role="header" data-theme="b">
  <h1>New Cafè</h1>
  <%= link_to 'Back', restaurants_path+'?filter1=now', 'data-icon' => 'back', 'class' => 'ui-btn-left', :target => '_parent' %>
</div>

<%= render 'form_new' %>

app/views/caves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cafe.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @cafe.address %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @cafe.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @cafe.lng %>
</p>

<p>
  <strong>Lm:</strong>
  <%= @cafe.LM %>
</p>

<p>
  <strong>Lp:</strong>
  <%= @cafe.LP %>
</p>

<p>
  <strong>Mm:</strong>
  <%= @cafe.MM %>
</p>

<p>
  <strong>Mp:</strong>
  <%= @cafe.MP %>
</p>

<p>
  <strong>Mem:</strong>
  <%= @cafe.MEM %>
</p>

<p>
  <strong>Mep:</strong>
  <%= @cafe.MEP %>
</p>

<p>
  <strong>Gm:</strong>
  <%= @cafe.GM %>
</p>

<p>
  <strong>Gp:</strong>
  <%= @cafe.GP %>
</p>

<p>
  <strong>Vm:</strong>
  <%= @cafe.VM %>
</p>

<p>
  <strong>Vp:</strong>
  <%= @cafe.VP %>
</p>

<p>
  <strong>Sm:</strong>
  <%= @cafe.SM %>
</p>

<p>
  <strong>Sp:</strong>
  <%= @cafe.SP %>
</p>

<p>
  <strong>Dm:</strong>
  <%= @cafe.DM %>
</p>

<p>
  <strong>Dp:</strong>
  <%= @cafe.DP %>
</p>

<%= link_to 'Edit', edit_cafe_path(@cafe) %> |
<%= link_to 'Back', caves_path %>