config/routes.rb
WiCity::Application.routes.draw do

  resources :links

  resources :nodos

  devise_for :users

  get '/users/sign_in', to: 'home#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :pharms
  resources :parks
  resources :taxistations
  resources :radiotaxis
  resources :fuels
  resources :restaurants
  resources :first_aids
  resources :hospitals
  resources :schools
  resources :caves

  root 'home#index'

  get '/intloc', to: 'home#intloc'
  get '/nearserv', to: 'home#nearserv'
  get '/recnearserv', to: 'home#recnearserv'

  get '/alllinks', to: 'links#showall'
  get '/allnodos', to: 'nodos#showall'

end

app/models/cafe.rb
class Cafe < ActiveRecord::Base
end

app/models/first_aid.rb
class FirstAid < ActiveRecord::Base
end

app/models/fuel.rb
class Fuel < ActiveRecord::Base

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/nodo.rb
class Nodo < ActiveRecord::Base
end

app/models/park.rb
class Park < ActiveRecord::Base

  validate :occupati_cannot_be_greater_than_capacity, :occupati_cannot_be_min_zero

  #validates :occupati, numericality: true
  validates :capacity, numericality: true

  def occupati_cannot_be_greater_than_capacity
    if !occupati.nil? && !capacity.nil?
      if occupati > capacity
        errors.add(:occupati, "can't be greater than capacity")
      end
    end
  end

  def occupati_cannot_be_min_zero
    if !occupati.nil?
      if occupati < 0
        errors.add(:occupati, "can't be less than zero")
      end
    end
  end

end

app/models/pharm.rb
class Pharm < ActiveRecord::Base
end

app/models/radiotaxi.rb
class Radiotaxi < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/taxistation.rb
class Taxistation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

  def intloc

  end

  def nearserv
    @pharms = Pharm.all
    @parks = Park.all
    @taxistations = Taxistation.all
    @radiotaxis = Radiotaxi.all
    @fuels = Fuel.all
    @restaurants = Restaurant.all
    @cafe = Cafe.all
  end

  def recnearserv
    @pharms = Pharm.all
    @parks = Park.all
    @taxistations = Taxistation.all
    @radiotaxis = Radiotaxi.all
    @fuels = Fuel.all
    @restaurants = Restaurant.all
    @cafe = Cafe.all
  end

end

app/helpers/caves_helper.rb
module CavesHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/nodos_helper.rb
module NodosHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/pharms_helper.rb
module PharmsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/home/BKintloc.html.erb
<script>
    /*$(function() {
        var $inner = $('#container');

        $inner.css({ marginTop:  ($(window).height() / 2) - $inner.outerHeight() / 2 });
    });*
</script>

<style>
    #mcs
    {
        background: -o-linear-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.60));
        background: linear-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.60));
        background: -webkit-linear-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.60));
        background: -webkit-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.60));
        height: 150px;
        width: 80%;
        box-shadow: 3px 3px 3px 3px;
    }

    #txt
    {
        font: small-caps bold 1.4em/2em Verdana, Arial, Helvetica, sans-serif;
        color: #EFEFEF;
        text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
    }

    #container
    {
        position: absolute;
        top: 50%;
        width: 100%;
        margin-top: -16.6em;
        margin-left: 2.8em;
    }

</style>

<div data-role="header">
  <h1>Main City Services</h1>
  <%= link_to 'Home', root_url, 'data-icon' => 'home', 'class' => 'ui-btn-left', 'data-iconpos' => 'notext', :target => '_parent' %>
</div>


<div data-role="content" id="container">

  <div class="ui-grid-b" style="margin-right: 2em">
    <div class="ui-block-a">
      <div class="button-wrap">
        <a href="<%= pharms_path %>?filter1=now" style="text-decoration: none" target="_parent">
          <button class="ui-shadow ui-btn ui-corner-all" id="mcs">
            <span id="txt">Pharms</span>
          </button>
        </a>
      </div>
    </div>

    <div class="ui-block-b">
      <div class="button-wrap">
        <a href="<%= hospitals_path %>?filter1=now" style="text-decoration: none" target="_parent">
          <button class="ui-shadow ui-btn ui-corner-all" id="mcs">
            <span id="txt">Hospitals &<br>Medical Guards</span>
          </button>
        </a>
      </div>
    </div>

    <div class="ui-block-c">
      <div class="button-wrap"><div class="button-wrap">
        <a href="<%= fuels_path %>?filter1=now" style="text-decoration: none" target="_parent">
          <button class="ui-shadow ui-btn ui-corner-all" id="mcs">
            <span id="txt">Fuel Stations</span>
          </button>
        </a>
      </div></div>
    </div>
  </div>

  <div class="ui-grid-b" style="margin-right: 2em">
    <div class="ui-block-a">
      <div class="button-wrap">
        <a href="<%= restaurants_path %>?filter1=now" style="text-decoration: none" target="_parent">
          <button class="ui-shadow ui-btn ui-corner-all" id="mcs">
            <span id="txt">Restaurants &<br>Café</span>
          </button>
        </a>
      </div>
    </div>

    <div class="ui-block-b">
      <div class="button-wrap">
        <button class="ui-shadow ui-btn ui-corner-all" id="mcs">
          <span id="txt">Bed and Breakfast &<br>Hotels</span>
        </button>
      </div>
    </div>

    <div class="ui-block-c">
      <div class="button-wrap">
        <button class="ui-shadow ui-btn ui-corner-all" id="mcs">
          <span id="txt">Cinema & Theaters</span>
        </button>
      </div>
    </div>
  </div>

  <div class="ui-grid-b" style="margin-right: 2em">
    <div class="ui-block-a">
      <div class="button-wrap">
        <button class="ui-shadow ui-btn ui-corner-all" id="mcs">
          <span id="txt">Schools & Universities</span>
        </button>
      </div>
    </div>

    <div class="ui-block-b">
      <div class="button-wrap">
        <button class="ui-shadow ui-btn ui-corner-all" id="mcs">
          <span id="txt">Financial Services &<br>City - Regional Stores</span>
        </button>
      </div>
    </div>

    <div class="ui-block-c">
      <div class="button-wrap">
        <a href="<%= parks_path %>?filter1=now" style="text-decoration: none" target="_parent">
          <button class="ui-shadow ui-btn ui-corner-all" id="mcs">
            <span id="txt">Parks - Garages &<br>Taxi Services</span>
          </button>
        </a>
      </div>
    </div>
  </div>

</div>

app/views/home/intloc.html.erb
<style>

    /* A bit custom styling */
    .my-page .ui-listview li .ui-btn p {
        color: #c0c0c0;
    }

    .my-page .ui-listview li .ui-btn h2 {
        color: #c0c0c0;
    }

    /* Hide the icon */
    .my-page .ui-listview .ui-btn-icon-right:after {
        display: none;
    }

    .my-page .ui-listview > li > a.ui-btn
    {
        background: -o-linear-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.6));
        background: linear-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.6));
        background: -webkit-linear-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.6));
        background: -webkit-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.6));
        border: 1px #000;
        box-shadow: 0px 0px 2px #111;
    }

    /* First breakpoint is 48em (768px). 3 column layout. Tiles 250x250 pixels incl. margin at the breakpoint. */
    @media ( min-width: 48em )
    {
        .my-page .ui-content {
            padding: .5625em; /* 9px */
        }

        .my-page .ui-listview li {
            float: left;
            width: 30.9333%; /* 33.3333% incl. 2 x 1.2% margin */
            height: 180px; /* 232p */
            margin: .5625em 1.2%;
        }

        .my-page .ui-listview li > .ui-btn {
            -webkit-box-sizing: border-box; /* include padding and border in height so we can set it to 100% */
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            height: 100%;
        }

        .my-page .ui-listview li.ui-li-has-thumb .ui-li-thumb {
            height: auto; /* To keep aspect ratio. */
            max-width: 100%;
            max-height: none;
            #display: none;
        }

        /* Make all list items and anchors inherit the border-radius from the UL. */
        .my-page .ui-listview li,
        .my-page .ui-listview li .ui-btn,
        .my-page .ui-listview .ui-li-thumb {
            -webkit-border-radius: inherit;
            border-radius: inherit;
        }

        /* Make text wrap. */
        .my-page .ui-listview h2,
        .my-page .ui-listview p {
            white-space: normal;
            overflow: visible;
            position: absolute;
            left: 0;
            right: 0;
        }

        /*.my-page .ui-listview li .ui-btn h2 {
            color: #000;
        }

        .my-page .ui-listview li .ui-btn p {
            color: #000;
        }*/

        /* Text position */
        .my-page .ui-listview h2 {
            font-size: 1.25em;
            margin: 0;
            padding: .125em 1em;
            bottom: 50%;
        }

        .my-page .ui-listview p {
            font-size: 1em;
            margin: 0;
            padding: 0 1.25em;
            min-height: 50%;
            bottom: 0;
        }

        /* Semi transparent background and different position if there is a thumb. The button has overflow hidden so we don't need to set border-radius. */
        .ui-listview .ui-li-has-thumb h2,
        .ui-listview .ui-li-has-thumb p {
            background: #111;
            background: rgba(0, 0, 0, 0.6);
        }

        .ui-listview .ui-li-has-thumb h2 {
            bottom: 35%;
        }

        .ui-listview .ui-li-has-thumb p {
            min-height: 35%;
        }

        /* If you want to add shadow, don't kill the focus style. */
        .my-page .ui-listview li {
            -moz-box-shadow: 0px 0px 9px #111;
            -webkit-box-shadow: 0px 0px 9px #111;
            box-shadow: 0px 0px 9px #111;
        }

        /* Images mask the hover bg color so we give desktop users feedback by applying the focus style on hover as well. */
        .my-page .ui-listview li > .ui-btn:hover {
            -moz-box-shadow: 0px 0px 12px #33ccff;
            -webkit-box-shadow: 0px 0px 12px #33ccff;
            box-shadow: 0px 0px 12px #33ccff;
        }

        /* Animate focus and hover style, and resizing. */
        .my-page .ui-listview li,
        .my-page .ui-listview .ui-btn {
            -webkit-transition: all 500ms ease;
            -moz-transition: all 500ms ease;
            -o-transition: all 500ms ease;
            -ms-transition: all 500ms ease;
            transition: all 500ms ease;
        }
    }

    /* Second breakpoint is 63.75em (1020px). 4 column layout. Tiles will be 250x250 pixels incl. margin again at the breakpoint. */
    @media ( min-width: 63.75em ) {
        .my-page .ui-content {
            padding: .625em; /* 10px */
        }
        /* Set a max-width for the last breakpoint to prevent too much stretching on large screens.
        By setting the max-width equal to the breakpoint width minus padding we keep square tiles. */
        .my-page .ui-listview {
            max-width: 1100px; /* 1000px */
            margin: 0 auto;
            margin-top: 50px;
        }
        /* Because of the 1000px max-width the width will always be 230px (and margin left/right 10px),
        but we stick to percentage values for demo purposes. */
        .my-page .ui-listview li {
            width: 23%;
            height: 230px;
            margin: .625em 1%;
        }
    }

</style>

<div data-role="header">
  <h1>Main City Services</h1>
  <%= link_to 'Home', root_url, 'data-icon' => 'home', 'class' => 'ui-btn-left', 'data-iconpos' => 'notext', :target => '_parent' %>
</div>




<div class="my-page">

  <div role="main" class="ui-content">

    <ul data-role="listview" data-inset="true">

      <li><a href="<%= pharms_path %>?filter1=now" target="_parent">
        <img src="/assets/icon_btn/pharms.png" class="ui-li-thumb">
        <h2>Pharms</h2>
        <p></p>
      </a></li>

      <li><a href="<%= hospitals_path %>?filter1=now" target="_parent">
        <img src="/assets/icon_btn/hospitals.png" class="ui-li-thumb">
        <h2>Hospitals</h2>
        <p></p>
      </a></li>

      <li><a href="#">
        <img src="/assets/icon_btn/hotels.png" class="ui-li-thumb">
        <h2>B&B - Hotels</h2>
        <p></p>
      </a></li>

      <li><a href="<%= restaurants_path %>?filter1=now" target="_parent">
        <img src="/assets/icon_btn/restaurants.png" class="ui-li-thumb">
        <h2>Restaurants & Café</h2>
        <p></p>
      </a></li>

      <!-- <li><a href="#">
        <img src="/assets/icon_btn/hospitals.png" class="ui-li-thumb">
        <h2>Cinema & Theaters</h2>
        <p></p>
      </a></li> -->

      <li><a href="#">
        <img src="/assets/icon_btn/financials.png" class="ui-li-thumb">
        <h2>Banks & Stores</h2>
        <p></p>
      </a></li>

      <li><a href="<%= schools_path %>" target="_parent">
        <img src="/assets/icon_btn/schools.png" class="ui-li-thumb">
        <h2>Schools & Universities</h2>
        <p></p>
      </a></li>

      <li><a href="<%= fuels_path %>?filter1=now" target="_parent">
        <img src="/assets/icon_btn/fuels.png" class="ui-li-thumb">
        <h2>Fuel Stations</h2>
        <p></p>
      </a></li>

      <li><a href="<%= parks_path %>?filter1=now" target="_parent">
        <img src="/assets/icon_btn/park.png" class="ui-li-thumb">
        <h2>Parks-Garages & Taxi</h2>
        <p></p>
      </a></li>

    </ul>
  </div>

</div>

app/views/home/intlocOK.html.erb
<style>

    .ui-listview > .ui-li-static, .ui-listview > .ui-li-divider, .ui-listview > li > a.ui-btn-mcs
    {
        background: -o-linear-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.6));
        background: linear-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.6));
        background: -webkit-linear-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.6));
        background: -webkit-gradient(to bottom right, rgba(0, 0, 0, 0.6), rgba(0, 0, 255, 0.6));
        border: 1px #000;
        box-shadow: 0px 0px 2px #111;
    }

    .ui-listview h2
    {
        color: #EFEFEF;
        text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
        text-align: center;
        font: small-caps bold 2em Verdana, Arial, Helvetica, sans-serif;
    }

    .ui-listview li .ui-btn p
    {
        color: #c0c0c0;
    }

    .ui-listview li .ui-btn
    {
        color: #eee;
    }

    /* 3 column layout */
    @media ( min-width: 768px )
    {
        .ui-content
        {
            padding: 9px;
            vertical-align: middle;
        }

        .ui-listview li
        {
            float: left;
            width: 30.9333%; /* 33.3333% incl. 2 x 1.2% margin */
            height: 150px;
            margin: .5625em 1.2%;
        }

        .ui-btn
        {
            border: 1px #000;
        }

        .ui-listview li > .ui-btn
        {
            -webkit-box-sizing: border-box; /* include padding and border in height so we can set it to 100% */
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            height: 100%;
        }

        /* Make all list items and anchors inherit the border-radius from the UL. */
        .ui-listview li, .ui-listview li .ui-btn
        {
            -webkit-border-radius: inherit;
            border-radius: inherit;
        }

        /* Hide the icon */
        .ui-listview .ui-btn-icon-right:after {
            display: none;
        }

        /* Make text wrap. */
        .ui-listview h2 {
            white-space: normal;
            overflow: visible;
            position: absolute;
            left: 0;
            right: 0;
        }

        /* Text position */
        .ui-listview h2 {
            font-size: 1.25em;
            margin: 0;
            padding: .125em 1em;
            bottom: 50%;
        }

        /* If you want to add shadow, don't kill the focus style. */
        .ui-listview li {
            -moz-box-shadow: 0px 0px 9px #111;
            -webkit-box-shadow: 0px 0px 9px #111;
            box-shadow: 0px 0px 9px #111;
        }

        /* Images mask the hover bg color so we give desktop users feedback by applying the focus style on hover as well. */
        .ui-listview li > .ui-btn:hover {
            -moz-box-shadow: 0px 0px 12px #33ccff;
            -webkit-box-shadow: 0px 0px 12px #33ccff;
            box-shadow: 0px 0px 12px #33ccff;
        }

        /* Animate focus and hover style, and resizing. */
        .ui-listview li, .ui-listview .ui-btn
        {
            -webkit-transition: all 500ms ease;
            -moz-transition: all 500ms ease;
            -o-transition: all 500ms ease;
            -ms-transition: all 500ms ease;
            transition: all 500ms ease;
        }
    }
</style>

<div data-role="header">
  <h1>Main City Services</h1>
  <%= link_to 'Home', root_url, 'data-icon' => 'home', 'class' => 'ui-btn-left', 'data-iconpos' => 'notext', :target => '_parent' %>
</div>


<div role="main" class="ui-content">
    <ul data-role="listview" data-inset="true">

      <li><a href="<%= pharms_path %>?filter1=now" target="_parent" class="ui-btn ui-btn-mcs">
        <img src="/assets/icon/openpharm.png" class="ui-li-thumb">
        <h2>Pharms</h2>
      </a></li>

      <li><a href="<%= hospitals_path %>?filter1=now" target="_parent" class="ui-btn ui-btn-mcs">
        <h2>Hospitals &<br>Medical Guards</h2>
      </a></li>

      <li><a href="" target="_parent" class="ui-btn ui-btn-mcs">
        <h2>Financial Services &<br>City - Regional Stores</h2>
      </a></li>

      <li><a href="<%= restaurants_path %>?filter1=now" target="_parent" class="ui-btn ui-btn-mcs">
        <h2>Restaurants &<br>Café</h2>
      </a></li>

      <li><a href="" target="_parent" class="ui-btn ui-btn-mcs">
        <h2>Bed and Breakfast &<br>Hotels</h2>
      </a></li>

      <li><a href="" target="_parent" class="ui-btn ui-btn-mcs">
        <h2>Cinema & Theaters</h2>
      </a></li>

      <li><a href="" target="_parent" class="ui-btn ui-btn-mcs">
        <h2>Schools & Universities</h2>
      </a></li>

      <li><a href="<%= fuels_path %>?filter1=now" target="_parent" class="ui-btn ui-btn-mcs">
        <h2>Fuel Stations</h2>
      </a></li>

      <li><a href="<%= parks_path %>?filter1=now" target="_parent" class="ui-btn ui-btn-mcs">
        <h2>Parks - Garages &<br>Taxi Services</h2>
      </a></li>

    </ul>
</div>