config/routes.rb
WiCity::Application.routes.draw do

  resources :links

  resources :nodos

  devise_for :users

  get '/users/sign_in', to: 'home#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :pharms
  resources :parks
  resources :taxistations
  resources :radiotaxis
  resources :fuels
  resources :restaurants
  resources :first_aids
  resources :hospitals
  resources :schools
  resources :caves

  root 'home#index'

  get '/intloc', to: 'home#intloc'
  get '/nearserv', to: 'home#nearserv'
  get '/recnearserv', to: 'home#recnearserv'

  get '/alllinks', to: 'links#showall'
  get '/allnodos', to: 'nodos#showall'

end

app/models/cafe.rb
class Cafe < ActiveRecord::Base
end

app/models/first_aid.rb
class FirstAid < ActiveRecord::Base
end

app/models/fuel.rb
class Fuel < ActiveRecord::Base

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/nodo.rb
class Nodo < ActiveRecord::Base
end

app/models/park.rb
class Park < ActiveRecord::Base

  validate :occupati_cannot_be_greater_than_capacity, :occupati_cannot_be_min_zero

  #validates :occupati, numericality: true
  validates :capacity, numericality: true

  def occupati_cannot_be_greater_than_capacity
    if !occupati.nil? && !capacity.nil?
      if occupati > capacity
        errors.add(:occupati, "can't be greater than capacity")
      end
    end
  end

  def occupati_cannot_be_min_zero
    if !occupati.nil?
      if occupati < 0
        errors.add(:occupati, "can't be less than zero")
      end
    end
  end

end

app/models/pharm.rb
class Pharm < ActiveRecord::Base
end

app/models/radiotaxi.rb
class Radiotaxi < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/taxistation.rb
class Taxistation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render action: 'show', status: :created, location: @school }
      else
        format.html { render action: 'new' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :address, :lat, :lng, :phone, :typ, :url)
    end
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/helpers/first_aids_helper.rb
module FirstAidsHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/nodos_helper.rb
module NodosHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/pharms_helper.rb
module PharmsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.number_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/_form_edit.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>

<script type="text/javascript">

    function initialize() {
        var input = (document.getElementById('school_address'));
        var autocomplete = new google.maps.places.Autocomplete(input);

        google.maps.event.addListener(autocomplete, 'place_changed', function() {

            var place = autocomplete.getPlace();
            if (!place.geometry) {
                return;
            }

            if (place.geometry.viewport) {
                map.fitBounds(place.geometry.viewport);
            } else {
                document.getElementById('school_lat').value = (place.geometry.location).lat();
                document.getElementById('school_lng').value = (place.geometry.location).lng();
                document.getElementById("school_add").style.display = "block";
            }
        });
    }

    function hideUpdate() {
        document.getElementById("school_add").style.display = "none";
    }

    google.maps.event.addDomListener(window, 'load', initialize);

</script>

<div data-role="content">

    <%= form_for(@school, :html => {:target => '_parent'} ) do |f| %>
      <% if @school.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

          <ul>
          <% @school.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <strong><b><%= f.label :Name, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
        <%= f.text_field :name %>
      </div>

      <br>

      <div class="field">
        <strong><b><%= f.label :Address, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
        <%= f.text_field :address, :onclick => 'hideUpdate();' %>
      </div>

      <br>

      <div class="ui-grid-a">
        <div class="ui-block-a" style="padding-right: 5px">
          <strong><b><%= f.label :Latitude, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
          <%= f.text_field :lat, :readonly => true %>
        </div>
        <div class="ui-block-b" style="padding-left: 5px">
          <strong><b><%= f.label :Longitude, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
          <%= f.text_field :lng, :readonly => true %>
        </div>
      </div>

      <br>

      <div class="ui-grid-a">
        <div class="ui-block-a" style="padding-right: 5px">
          <strong><b><%= f.label :Phone, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
          <%= f.text_field :phone %>
        </div>
        <div class="ui-block-b" style="padding-left: 5px">
          <strong><b><%= f.label :Site, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
          <%= f.text_field :url %>
        </div>
      </div>

      <br>

      <div id="school_add" class="actions">
        <%= f.submit %>
      </div>

    <% end %>

</div>

app/views/schools/_form_new.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>

<script>

    function initialize() {

        var input = (document.getElementById('school_address'));
        var autocomplete = new google.maps.places.Autocomplete(input);

        google.maps.event.addListener(autocomplete, 'place_changed', function() {

            var place = autocomplete.getPlace();
            if (!place.geometry) {
                return;
            }

            if (place.geometry.viewport) {
                map.fitBounds(place.geometry.viewport);
            } else {
                document.getElementById('school_lat').value = (place.geometry.location).lat();
                document.getElementById('school_lng').value = (place.geometry.location).lng();
                document.getElementById("school_add").style.display = "block";
            }
        });
    }

    google.maps.event.addDomListener(window, 'load', initialize);

</script>



<div data-role="content">

    <%= form_for(@school, :html => {:target => '_parent'} ) do |f| %>
      <% if @school.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

          <ul>
          <% @school.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <strong><b><%= f.label :Name, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
        <%= f.text_field :name %>
      </div>

      <br>

      <div class="field">
        <strong><b><%= f.label :Address, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
        <%= f.text_field :address %>
      </div>

      <br>

      <div class="ui-grid-a">
        <div class="ui-block-a" style="padding-right: 5px">
          <strong><b><%= f.label :Latitude, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
          <%= f.text_field :lat, :readonly => true %>
        </div>
        <div class="ui-block-b" style="padding-left: 5px">
          <strong><b><%= f.label :Longitude, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
          <%= f.text_field :lng, :readonly => true %>
        </div>
      </div>

      <br>

      <div class="field">
        <strong><b><%= f.label :Site, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
        <%= f.text_field :url %>
      </div>

      <br>

      <div class="ui-grid-a">
        <div class="ui-block-a" style="padding-right: 5px">
          <strong><b><%= f.label :Phone, :class => "ui-bar ui-bar-a ui-corner-all ui-shadow" %></b></strong>
          <%= f.text_field :phone %>
        </div>

        <div class="ui-block-b" style="padding-left: 5px">
          <div class="ui-grid-c ui-corner-all">
            <div class="ui-block-a">
              <div class="ui-bar ui-bar-a" style="height:60px">
                Scuola Elementare
                <label style="height: 10px"><%= f.radio_button(:typ, 0) %></label>
              </div>
            </div>
            <div class="ui-block-b">
              <div class="ui-bar ui-bar-a" style="height:60px">
                Scuola Media
                <label style="height: 10px"><%= f.radio_button(:typ, 1) %></label>
              </div>
            </div>
            <div class="ui-block-c">
              <div class="ui-bar ui-bar-a" style="height:60px">
                Scuola Superiore
                <label style="height: 10px"><%= f.radio_button(:typ, 2) %></label>
              </div>
            </div>
            <div class="ui-block-d">
              <div class="ui-bar ui-bar-a" style="height:60px">
                Università
                <label style="height: 10px"><%= f.radio_button(:typ, 3) %></label>
              </div>
            </div>
          </div>
        </div>

      </div>

      <br>

      <div class="actions" id="school_add" style="display:none;">
        <%= f.submit 'Add School' %>
      </div>

    <% end %>

</div>

app/views/schools/edit.html.erb
<div data-role="header" data-theme="b">
  <h1>Edit School</h1>
  <%= link_to 'Back', schools_path, 'data-icon' => 'back', 'class' => 'ui-btn-left', :target => '_parent' %>
  <%= link_to 'Show', @school, :target => '_parent', 'data-icon' => 'search', 'class' => 'ui-btn-right'  %>
</div>

<%= render 'form_edit' %>

app/views/schools/index.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.9.1.js"></script>
<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

<link rel="stylesheet" type="text/css" href="assets/jquery.datetimepicker.css">
<script src="assets/jquery.datetimepicker.js"></script>

<script>

    $(function() {
        <% if params[:filter] == 'all' %>
        $( "#filterall" ).css("border-color", "red");
        $( "#filterall" ).css("border-width", "2px");
        <% else %>
        $( "#filteropen" ).css("border-color", "red");
        $( "#filteropen" ).css("border-width", "2px");
        <% end %>

        <% if params[:filter1] == 'now' %>
        $( "#filternow" ).css("height", "18px");
        $( "#filternow" ).css("border-color", "red");
        $( "#filternow" ).css("border-width", "2px");
        <% end %>

        <% if params[:filter2] == 'notturne' %>
        $( "#filternotturne" ).css("height", "18px");
        $( "#filternotturne" ).css("border-color", "red");
        $( "#filternotturne" ).css("border-width", "2px");
        <% end %>

        <% if params[:day] == '7' %>
        $( "#filtersunday" ).css("height", "18px");
        $( "#filtersunday" ).css("border-color", "red");
        $( "#filtersunday" ).css("border-width", "2px");
        <% end %>
    });
</script>


<div data-role="header" data-theme="b">
  <h1>Schools & University</h1>
  <div id="custom-border-radius" class="ui-btn-left" data-role="controlgroup" data-type="horizontal" data-mini="true">
    <%= link_to 'Back', 'intloc', 'data-icon' => 'back', 'data-role' => 'button', 'data-iconpos' => 'notext' %>
    <%= link_to 'Home', root_url, 'data-icon' => 'home', 'data-role' => 'button', 'data-iconpos' => 'notext', :target => '_parent' %>
  </div>
  <%= link_to 'Add', new_school_path, 'data-iconpos' => 'notext', 'data-icon' => 'plus', 'class' => 'ui-btn-right', :target => '_parent' %>
</div>


<div data-role="content">

  <ul data-role="listview" data-inset="true" data-filter="true">
    <% @schools.each do |school|  %>
        <li>
          <a href="<%= "#{schools_url}/#{school.id}" %>" target="_parent">
          <!-- <img src="/assets/icon/school.png"> -->
          <h2><%= school.name %></h2>
          <p><%= school.address %></p>
          <%= link_to 'Edit', edit_school_path(school), 'data-icon' => 'edit', :target => '_parent' %>
          </a>
        </li>
    <% end %>
  </ul>
</div>

app/views/schools/new.html.erb
<div data-role="header" data-theme="b">
  <h1>New School</h1>
  <%= link_to 'Back', schools_path, 'data-icon' => 'back', 'class' => 'ui-btn-left', :target => '_parent' %>
</div>

<%= render 'form_new' %>

app/views/schools/show.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true"></script>

<script type="text/javascript">

    var map;
    var geocoder;
    var mypos = 0;

    var check = 0;

    var directionsDisplay;
    var directionsService = new google.maps.DirectionsService();

    var stepDisplay;
    var markerArray = [];

    var intervall = window.setInterval(checkpos, 2000);

    function checkpos() {
        if(mypos == 0) {
            check++;
            preinit();
        }
    }

    function preinit() {
        geocoder = new google.maps.Geocoder();

        var lat = "<%= params[:lat] %>";
        var lng = "<%= params[:lng] %>";
        if(lat) {
            mypos = new google.maps.LatLng(lat, lng);
            window.clearInterval(intervall);
            initialize();
        }
        else {
            if(check > 1) {
                window.clearInterval(intervall);
                initialize();
            }
            else {
                if(navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(function(position) {
                        if(position.coords.latitude) {
                            mypos = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                            window.clearInterval(intervall);
                            initialize();
                        }
                    }, function() {
                        handleNoGeolocation(true);
                    });
                } else {
                    handleNoGeolocation(false);
                }
            }
        }
    }

    function codeAdd(add) {
        geocoder.geocode( { 'address': add}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                mypos = results[0].geometry.location;
            } else {
                mypos = 0;
            }
            window.clearInterval(intervall);
            initialize();
        });
    }

    function handleNoGeolocation(errorFlag) {
        if (errorFlag) {
            alert("Error: The Geolocation service failed.");
        } else {
            alert("Error: Your browser doesn\'t support geolocation.");
        }
    }

    function initialize() {
        if(mypos == 0) {
            <% if user_signed_in? %>
            if("<%= current_user.prefadd %>" == "away") {
                codeAdd("<%= current_user.away %>");
            }
            else if("<%= current_user.prefadd %>" == "home") {
                codeAdd("<%= current_user.home %>");
            }
            else if("<%= current_user.prefadd %>" == "office") {
                codeAdd("<%= current_user.office %>");
            }
            else if("<%= current_user.prefadd %>" == "other") {
                codeAdd("<%= current_user.other %>");
            }
            else {
                mypos = new google.maps.LatLng(37.508059, 375.082752);
            }
            <% else %>
            mypos = new google.maps.LatLng(37.508059, 375.082752);
            <% end %>
        }

        directionsDisplay = new google.maps.DirectionsRenderer({suppressMarkers: true});

        var mapOptions = {
            center: new google.maps.LatLng(-34.397, 150.644),
            zoom: 17,
            minZoom: 12,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
        directionsDisplay.setMap(map);

        directionsDisplay.setPanel(document.getElementById('directions-panel'));
        $( "#directions-panel" ).trigger( "updatelayout" );

        stepDisplay = new google.maps.InfoWindow();

        codeAddress("<%= @school.address %>");
    }

    function codeAddress(add) {
        var address = add;
        var s = "<%= params[:s] %>";
        geocoder.geocode( { 'address': address}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                map.setCenter(results[0].geometry.location);
                var icon = '/assets/marker/school.png';
                var marker = new google.maps.Marker({
                    map: map,
                    position: results[0].geometry.location,
                    icon: icon
                });
                google.maps.event.addListener(marker, "dblclick", function (e) {
                    <%    if params[:time]   %>
                    location.href='../nearserv?lat='+e.latLng.lat()+'&lng='+e.latLng.lng()+'&time=<%= params[:time] %>';
                    <%    else   %>
                    location.href='../nearserv?lat='+e.latLng.lat()+'&lng='+e.latLng.lng();
                    <%    end   %>
                });
            } else {
                alert("Geocode was not successful for the following reason: " + status);
            }
        });
    }

    function calcRoute(mode) {

        for (var i = 0; i < markerArray.length; i++) {
            markerArray[i].setMap(null);
        }

        var selectedMode = mode;
        var request = {
            origin: mypos,
            destination: "<%= @school.address %>",
            travelMode: google.maps.TravelMode[selectedMode]
        };
        directionsService.route(request, function(response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
                showSteps(response);
            }
        });
    }

    function showSteps(directionResult) {
        var myRoute = directionResult.routes[0].legs[0];

        for (var i = 0; i < myRoute.steps.length; i++) {
            var marker = new google.maps.Marker({
                position: myRoute.steps[i].start_point,
                map: map
            });
            attachInstructionText(marker, myRoute.steps[i].instructions);
            markerArray[i] = marker;

            google.maps.event.addListener(marker, "dblclick", function (e) {
                <%    if params[:time]   %>
                location.href='../nearserv?lat='+e.latLng.lat()+'&lng='+e.latLng.lng()+'&time=<%= params[:time] %>';
                <%    else   %>
                location.href='../nearserv?lat='+e.latLng.lat()+'&lng='+e.latLng.lng();
                <%    end   %>
            });
        }
    }

    function attachInstructionText(marker, text) {
        google.maps.event.addListener(marker, 'click', function() {
            stepDisplay.setContent(text);
            stepDisplay.open(map, marker);
        });
    }

    //google.maps.event.addDomListener(window, 'load', preinit);
    //google.maps.event.addDomListener(window, 'load', initialize);

</script>

<style>
    .ui-panel-inner {
        overflow: scroll;
        -webkit-overflow-scrolling: touch;
    }

    .ui-panel.ui-panel-open {
        position:fixed;
    }

    #directions-panel {
        height: 100%;
        overflow: auto;
        -webkit-overflow-scrolling: touch;
    }

</style>

<div data-role="header" data-theme="b">
  <h1><%= @school.name %></h1>
  <div class="ui-btn-left" data-role="controlgroup" data-type="horizontal" data-mini="true">
    <%= link_to 'Back', schools_path, 'data-icon' => 'back', 'data-role' => 'button', 'data-iconpos' => 'notext', :target => '_parent' %>
    <%= link_to 'Home', root_url, 'data-icon' => 'home', 'data-role' => 'button', 'data-iconpos' => 'notext', :target => '_parent' %>
  </div>
  <%= link_to 'Edit', edit_school_path(@school), 'data-icon' => 'edit', 'class' => 'ui-btn-right', 'data-iconpos' => 'notext', :target => '_parent' %>
</div>


<div data-role="content">

  <div class="ui-bar ui-bar-c ui-corner-all ui-shadow">
    <div id="map-canvas" style="width: 100%; height: 400px" class="ui-corner-all ui-shadow"></div>
  </div>

  <div class="ui-grid-a ui-responsive">
    <div class="ui-block-a">
      <a href="#popupMenu" data-rel="popup" data-role="button" data-position-to='window' data-transition="slideup" data-icon="gear" data-theme="b">Get Direction</a>
    </div>
    <div class="ui-block-b">
      <a href="#directions-panel" data-role="button" data-transition="slideup" data-icon="gear" data-theme="b">Panel</a>
    </div>
  </div>

  <div>
    <div data-role="popup" id="popupMenu">
      <a href="#" data-rel="back" data-role="button" data-theme="a" data-icon="delete" data-iconpos="notext" class="ui-btn-right">Close</a>
      <ul data-role="listview" data-inset="true" style="min-width:210px;">
        <li><a href="" onclick="calcRoute('DRIVING');" data-rel="back">Driving</a></li>
        <li><a href="" onclick="calcRoute('WALKING');" data-rel="back">Walking</a></li>
        <li><a href="" onclick="calcRoute('BICYCLING');" data-rel="back">Bicycling</a></li>
      </ul>
    </div>
  </div>

  <!-- <div id="directions-panel"></div> -->

  <div data-role="panel" id="directions-panel" data-display="overlay" class="ui-responsive-panel"></div>

  <p class="ui-bar ui-bar-a ui-corner-all ui-shadow">
    <strong>Address:</strong>
    <%= @school.address %>
  </p>

  <div class="ui-grid-a">
    <div class="ui-block-a">
      <p class="ui-bar ui-bar-a ui-corner-all ui-shadow">
        <strong>Site:</strong>
        <a data-role="none" href="<%= @school.url %>" target="_blank"><%= @school.url %></a>
      </p>
    </div>

    <div class="ui-block-b">
      <p class="ui-bar ui-bar-a ui-corner-all ui-shadow">
        <strong>Phone:</strong>
        <%= @school.phone %>
      </p>
    </div>
  </div>

</div>